//
//  CStructGenerator.cpp
//  Il2ccpDumper
//
//  Created by ts1 on 26/05/2026.
//

#include "CStructGenerator.h"

#include <cstdio>

namespace Il2Dumper
{
    bool CStructGenerator::WriteHeader(const std::string& m_OutDir)
    {
        std::string m_Path = m_OutDir + "il2cpp.h";
        FILE* p_F = std::fopen(m_Path.c_str(), "wb");
        if (!p_F) return false;

        std::fprintf(p_F,
            "// Generated by Il2ccpDumper\n"
            "#pragma once\n"
            "#include <stdint.h>\n\n"
            "typedef void* Il2CppObject;\n"
            "typedef void* Il2CppClass;\n"
            "typedef void* Il2CppType;\n\n");

        CMetadata* p_Meta = p_Exec_->Meta();
        for (size_t i = 0; i < p_Meta->TypeDefs().size(); ++i)
        {
            const STypeDefinition& m_Td = p_Meta->TypeDefs()[i];
            std::string m_Ns = p_Meta->GetStringFromIndex(m_Td.m_NamespaceIndex);
            std::string m_Nm = p_Meta->GetStringFromIndex(m_Td.m_NameIndex);

            // Sanitize name into a C identifier.
            std::string m_Id = m_Nm;
            for (auto& c : m_Id) { if (!(isalnum(uint8_t(c)) || c == '_')) c = '_'; }
            if (!m_Id.empty() && isdigit(uint8_t(m_Id.front()))) m_Id.insert(m_Id.begin(), '_');

            std::fprintf(p_F, "// %s.%s (TypeDefIndex=%zu)\nstruct %s_%zu { Il2CppObject __obj; };\n\n",
                         m_Ns.c_str(), m_Nm.c_str(), i, m_Id.c_str(), i);
        }

        std::fclose(p_F);
        return true;
    }
}
